core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

djangowebchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('rooms/', include('room.urls')),
]

room/urls.py
from django.urls import path

from . import views

app_name = 'room'

urlpatterns = [
    path('', views.rooms, name='rooms'),
    path('<str:slug>/', views.details, name='details'),
]

core/models.py
from django.db import models

# Create your models here.

room/models.py
from django.db import models

from django.contrib.auth.models import User

class Rooms(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Rooms'
    
    def __str__(self):
        return self.name
    
class Message(models.Model):
    room = models.ForeignKey(Rooms, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_added',)

core/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginFrom(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login

from .forms import SignUpForm

def frontpage(request):
    return render(request, 'core/frontpage.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            userform = form.save()

            login(request, userform)

            return redirect('core:frontpage')
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {'form': form})

room/views.py
from django.shortcuts import render

from .models import Rooms, Message

def rooms(request):
    rooms = Rooms.objects.all()
    return render(request, 'room/rooms.html', {'rooms': rooms})

def details(request, slug):
    room = Rooms.objects.get(slug=slug)
    messages = Message.objects.filter(room=room)
    return render(request, 'room/details.html', {'room': room, 'messages': messages})

core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Djangochat</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>

    {% include 'core/navbar.html' %}

    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Front page{% endblock %}

{% block content %}
    frontpage!!!
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<form method="POST" action=".">
    {% csrf_token %}

    <div>
        <p>Your username:</p>
        <input type="text" name="username" placeholder="Your username...">
    </div>
    <div>
        <p>Your password:</p>
        <input type="password" name="password" placeholder="Your password...">
    </div>

    {% if form.errors or form.non_field_errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p>{{ error|escape }}</p>
            {% endfor %}
        {% endfor %}

        {{ form.non_field_errors }}
    {% endif %}

    <br/>
    <button class="btn btn-success">Log in</button>
</form>


{% endblock %}

core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Djangochat</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
            <a href="/rooms/" class="btn btn-success">Rooms</a>
            <a href="{% url 'core:logout' %}" class="btn btn-secondary">Logout</a>
        
        {% else %}
            <a href="{% url 'core:signup' %}" class="btn btn-success">Sign up</a>
            <a href="/login/" class="btn btn-secondary">Log in</a>
        {% endif %}
      </div>

  </nav>

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<form method="POST" action=".">
    {% csrf_token %}

    <div>
        <p>Your username:</p>
        <input type="text" name="username" placeholder="Your username...">
    </div>
    <div>
        <p>Your password:</p>
        <input type="password" name="password1" placeholder="Your password...">
    </div>
    <div>
        <p>Repeat password:</p>
        <input type="password" name="password2" placeholder="Repeat password...">
    </div>

    {% if form.errors or form.non_field_errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p>{{ error|escape }}</p>
            {% endfor %}
        {% endfor %}

        {{ form.non_field_errors }}
    {% endif %}

    <br/>
    <button class="btn btn-success">Submit</button>
</form>


{% endblock %}

room/templates/room/details.html
{% extends 'core/base.html' %}

{% block title %}{{ room.name }}{% endblock %}

{% block content %}
<h1>{{ room.name }}</h1>

<div id="chat-messages">
    {% for message in messages %}
        <div>
            <h3>{{ message.user.username }}</h3>
            <p>{{ message.content }}</p>
        </div>
    {% endfor %}
</div>

<div>
    <form method="POST" action=".">
        <input type="text" name="content" placeholder="Enter your message..." id="chat-message-input"><br/>
    
        <button class="btn btn-success" id="chat-message-submit">Submit</button>    
    </form>    
</div>
{% endblock %}

{% block scripts %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        console.log('onmessage')

        const data = JSON.parse(e.data);

        if (data.message) {
            let html = '<div>';
                html += '<p>' + data.username + '</p>';
                html += '<p>' + data.message + '</p>';

            document.querySelector('#chat-messages').innerHTML += html;

        } else {
            alert('The message was empty!')
        }
    }

    chatSocket.onclose = function(e) {
        console.log('onclose')
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault();

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }))

        messageInputDom.value = '';

        return false;
    }
</script>
{% endblock %}

room/templates/room/rooms.html
{% extends 'core/base.html' %}

{% block title %}Rooms{% endblock %}

{% block content %}
<h1>Rooms</h1>
{% for room in rooms %}
    <div>
        <h1>{{ room.name }}</h1>
        <a href="{% url 'room:details' room.slug %}" class="btn btn-success">Join room</a>
    </div>
{% endfor %}

{% endblock %}